//
//  AuthViewController.swift
//  AIRENAMVP
//
//  Created by Haik Ampardjian on 8/30/17.
//  Copyright (c) 2017 challengeme llc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol AuthDisplayLogic: class
{
    func displaySomething(viewModel: Auth.Something.ViewModel)
}

class AuthViewController: UIViewController, AuthDisplayLogic
{
    var interactor: AuthBusinessLogic?
    var router: (NSObjectProtocol & AuthRoutingLogic & AuthDataPassing)?
    
    @IBOutlet weak var spinnerBox: UIView!
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = AuthInteractor()
        let presenter = AuthPresenter()
        let router = AuthRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        startPlaceholderTimer()
    }
    
    func startPlaceholderTimer() {
        WalletResponse.loadType(request: API.etheriumCreateWallet()) { (resp, error) in
            if error == nil {
                dump(resp)
                AppSettings.shared.save(wallet: resp!)
                (UIApplication.shared.delegate as? AppDelegate)?.showHome()
            }
        }
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = Auth.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Auth.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
