//
//  WalletPresenter.swift
//  AIRENAMVP
//
//  Created by Haik Ampardjian on 8/30/17.
//  Copyright (c) 2017 challengeme llc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletPresentationLogic
{
  func presentSomething(response: Wallet.Something.Response)
}

class WalletPresenter: WalletPresentationLogic
{
  weak var viewController: WalletDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Wallet.Something.Response)
  {
    let viewModel = Wallet.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
