//
//  WalletInteractor.swift
//  AIRENAMVP
//
//  Created by Haik Ampardjian on 8/30/17.
//  Copyright (c) 2017 challengeme llc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletBusinessLogic
{
  func doSomething(request: Wallet.Something.Request)
}

protocol WalletDataStore
{
  //var name: String { get set }
}

class WalletInteractor: WalletBusinessLogic, WalletDataStore
{
  var presenter: WalletPresentationLogic?
  var worker: WalletWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Wallet.Something.Request)
  {
    worker = WalletWorker()
    worker?.doSomeWork()
    
    let response = Wallet.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
