language: objective-c
osx_image: xcode7.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8

script:
  - xcodebuild test -workspace JSONRPCKit.xcworkspace -scheme JSONRPCKit-iOS -sdk iphonesimulator | xcpretty -c
  - xcodebuild build -workspace JSONRPCKit.xcworkspace -scheme Example -sdk iphonesimulator | xcpretty -c

notifications:
  email: false
