//
//  CreateInteractor.swift
//  AIRENAMVP
//
//  Created by Haik Ampardjian on 8/30/17.
//  Copyright (c) 2017 challengeme llc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateBusinessLogic
{
  func doSomething(request: Create.Something.Request)
}

protocol CreateDataStore
{
  //var name: String { get set }
}

class CreateInteractor: CreateBusinessLogic, CreateDataStore
{
  var presenter: CreatePresentationLogic?
  var worker: CreateWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Create.Something.Request)
  {
    worker = CreateWorker()
    worker?.doSomeWork()
    
    let response = Create.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
