//
//  CreatePresenter.swift
//  AIRENAMVP
//
//  Created by Haik Ampardjian on 8/30/17.
//  Copyright (c) 2017 challengeme llc. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreatePresentationLogic
{
  func presentSomething(response: Create.Something.Response)
}

class CreatePresenter: CreatePresentationLogic
{
  weak var viewController: CreateDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Create.Something.Response)
  {
    let viewModel = Create.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
